---
platforms:
  - name: fedora-27
    groups:
      - consul_instances
    image: dokken/fedora-27
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
