---
collections:
  - name: ansible.utils
    version: 2.6.1
  - name: ansible.windows
    version: 1.13.0
  - name: community.general
    version: 8.1.0
  - name: community.windows
    version: 2.1.0
