---
# File: config.yml - Consul configuration tasks

- name: Create configuration
  ansible.builtin.copy:
    dest: "{{ config_item.dest }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    content: "{{ lookup('template', consul_config_template_path, convert_data=True) | to_nice_json }}"
    mode: "0600"
  with_items:
    - dest: "{{ consul_config_path }}/config.json"
      config_version: "{{ consul_node_role }}"
      when: true
    - dest: "{{ consul_config_path }}/bootstrap.json"
      config_version: bootstrap
      when: "{{ consul_debug | bool }}"
    - dest: "{{ consul_config_path }}/server.json"
      config_version: server
      when: "{{ consul_debug | bool }}"
    - dest: "{{ consul_config_path }}/client.json"
      config_version: client
      when: "{{ consul_debug | bool }}"
  loop_control:
    loop_var: config_item
  when: config_item.when
  notify:
    - restart consul

- name: Create custom configuration
  ansible.builtin.copy:
    dest: "{{ consul_configd_path }}/50custom.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    content: "{{ lookup('template', 'templates/configd_50custom.json.j2', convert_data=True) | to_nice_json }}"
    mode: "0600"
  when: consul_config_custom is defined
  notify:
    - restart consul

- name: Set fact list with custom configuration file
  ansible.builtin.set_fact:
    managed_files: "{{ managed_files | default([]) }} + [ '{{ consul_configd_path }}/50custom.json' ]"

# All configuration files must be given to the validate command at once (partial conf might raise some issue regarding missing some required items), so it's not possible to use the validate arg og the ansibvle.builtin.copy module used to template the config
- name: Validate configuration
  become: true
  become_user: "{{ consul_user }}"
  ansible.builtin.command: >
    {{ consul_binary }} validate {{ (ansible_verbosity == 0) | ternary("-quiet", "") }}
    {{ consul_config_path }}/config.json {{ consul_configd_path }}
  changed_when: false
