---
# vim: set softtabstop=2 tabstop=2 shiftwidth=2 expandtab autoindent smartindent syntax=yaml:

- name: Create configuration
  copy:
    content: "{{ consul_config_merged | to_nice_json }}"
    dest: "{{ consul_config_path }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  notify:
    - restart consul
