---
# File: dnsmasq.yml - Dnsmasq tasks for Consul

- name: Install Dnsmasq package
  package:
    name: "{{ dnsmasq_package }}"
    state: present
  tags: dnsmasq, installation

- name: Create Dnsmasq configuration directory
  file:
    path: /usr/local/etc/dnsmasq.d
    state: directory
    owner: root
    group: wheel
    mode: 0700
  when: ansible_os_family == "FreeBSD"
  tags: dnsmasq

- name: Include Dnsmasq configuration directory
  lineinfile:
    dest: /usr/local/etc/dnsmasq.conf
    line: 'conf-dir=/usr/local/etc/dnsmasq.d/,*.conf'
  notify: restart dnsmasq
  when: ansible_os_family == "FreeBSD"
  tags: dnsmasq

- name: Create Dnsmasq configuration
  template:
    src: dnsmasq-10-consul.j2
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: 0644
  notify: restart dnsmasq
  when: item.when
  tags: dnsmasq
  loop:
    - { dest: '/etc/dnsmasq.d/10-consul', group: 'root', when: ansible_os_family|lower != "freebsd" }
    - { dest: '/usr/local/etc/dnsmasq.d/consul.conf', group: 'wheel', when: ansible_os_family|lower == "freebsd" }
