---
# File: install_linux_repo.yml - package installation tasks for Consul

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ consul_repo_prerequisites }}"
    state: present
  become: true
  when: (consul_os_repo_prerequisites)
  tags: installation

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Clean up previous consul data
  when: "'consul' not in ansible_facts.packages"
  become: true
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Stop service consul, if running
      ansible.builtin.service:
        name: "{{ consul_systemd_service_name }}"
        state: stopped
        # Needed to force SysV service manager on Docker for Molecule tests
        use: "{{ ansible_service_mgr }}"
      when: ansible_facts.services | join is match('.*consul.*')

    - name: Remove consul service unit files from previous installation
      ansible.builtin.file:
        path: "{{ service_unit_item }}"
        state: absent
      loop:
        - /usr/lib/systemd/system/consul.service
        - /etc/init.d/consul
      loop_control:
        loop_var: service_unit_item

    - name: Remove the user 'consul'
      ansible.builtin.user:
        name: consul
        state: absent
        remove: true

- name: Install repository
  when: ansible_os_family|lower in [ 'debian', 'redhat' ]
  become: true
  block:
    - name: Add Redhat/CentOS/Fedora/Amazon Linux repository
      ansible.builtin.command: yum-config-manager --add-repo {{ consul_repo_url }}
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
      when: >
        ansible_distribution|lower == 'redhat' or
        ansible_distribution|lower == 'centos' or
        ansible_distribution|lower == 'fedora' or
        ansible_distribution|lower == 'amazon' or
        ansible_distribution|lower == 'rocky' or
        ansible_distribution|lower == 'almalinux'


    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: "{{ consul_repo_url }}/gpg"
        state: present
      when: ansible_os_family|lower == 'debian'

    - name: Add Debian/Ubuntu Linux repository
      ansible.builtin.apt_repository:
        repo: deb {{ consul_repo_url }} {{ ansible_distribution_release }} main
        state: present
        update_cache: true
      when: ansible_os_family|lower == 'debian'

- name: Install consul package
  ansible.builtin.package:
    name: consul{{ '=' if ansible_pkg_mgr == 'apt' else '-' }}{{ consul_version }}
    state: present
  become: true

- name: "Create a directory /etc/systemd/system/{{ consul_systemd_service_name }}.service.d"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ consul_systemd_service_name }}.service.d"
    state: directory
    mode: "0755"
    owner: root
    group: root
  register: systemd_override
  become: true
  when: ansible_service_mgr == "systemd"

- name: Override systemd service params
  ansible.builtin.template:
    src: consul_systemd_service.override.j2
    dest: "/etc/systemd/system/{{ consul_systemd_service_name }}.service.d/override.conf"
    owner: root
    group: root
    mode: "0644"
  register: systemd_override
  become: true
  notify:
    - systemctl daemon-reload
    - restart consul
  when:
    - ansible_service_mgr == "systemd"
    - consul_install_from_repo | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: As, this role work with json conf file only - delete file /etc/consul.d/consul.hcl
  ansible.builtin.file:
    path: /etc/consul.d/consul.hcl
    state: absent
  become: true
