---
# File: install_linux_repo.yml - package installation tasks for Consul

- name: Install OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Populate service facts
  service_facts:

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Clean up previous consul data
  block:
    - name: Stop service consul, if running
      systemd:
        name: consul
        state: stopped
      when: ansible_facts.services['consul.service'] is defined

    - name: Remove consul systemd unit file from previous installation
      file:
        path: /usr/lib/systemd/system/consul.service
        state: absent
      notify: systemctl daemon-reload

    - name: Remove the user 'consul'
      user:
        name: consul
        state: absent
        remove: yes

  when:
    - "ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos' or \
        ansible_distribution|lower == 'fedora' or ansible_distribution|lower == 'amazon' or \
        ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'"
    - "'consul' not in ansible_facts.packages"

- name: Install repository
  block:
    - name: Add Redhat/CentOS/Fedora/Amazon Linux repository
      command: "yum-config-manager --add-repo {{ consul_repo_url }}"
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
      when: "ansible_distribution|lower == 'redhat' or ansible_distribution|lower == 'centos' or \
            ansible_distribution|lower == 'fedora' or ansible_distribution|lower == 'amazon'"


    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'

    - name: Add Debian/Ubuntu Linux repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        update_cache: true
      when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'

- name: Install consul package
  package:
    name: "consul{{ '=' if ansible_pkg_mgr == 'apt' else '-' }}{{ consul_version }}"
    state: present

- name: Create a directory /etc/systemd/system/consul.service.d
  file:
    path: /etc/systemd/system/consul.service.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  register: systemd_override


- name: Override systemd service params
  template:
    src: consul_systemd_service.override.j2
    dest: /etc/systemd/system/consul.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  register: systemd_override
  notify:
    - systemctl daemon-reload
    - restart consul
  when:
    - ansible_service_mgr == "systemd"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"
    - consul_install_from_repo | bool

- name: Flush handlers
  meta: flush_handlers

- name: As, this role work with json conf file only - delete file /etc/consul.d/consul.hcl
  file:
    path: /etc/consul.d/consul.hcl
    state: absent
