---
# File: iptables.yml - iptables tasks for Consul

- name: Install iptables
  ansible.builtin.apt:
    name: iptables

- name: Redirect local DNS (1/4)
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: udp
    match: udp
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600

- name: Redirect local DNS (2/4)
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600

- name: Redirect local DNS (3/4)
  ansible.builtin.iptables:
    table: nat
    chain: OUTPUT
    protocol: udp
    match: udp
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600
    destination: localhost

- name: Redirect local DNS (4/4)
  ansible.builtin.iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600
    destination: localhost
