---
# File: user_group.yml - User and group settings

# Add group
- name: Add Consul group
  group:
    name: "{{ consul_group }}"
    state: present
  when:
    - consul_manage_group | bool
    - not consul_install_from_repo | bool

# Add user
- name: Add Consul user
  user:
    name: "{{ consul_user }}"
    comment: "Consul user"
    group: "{{ consul_group }}"
    system: true
  when:
    - consul_manage_user | bool
    - not consul_install_from_repo | bool
