---
platforms:
  - name: debian-8
    groups:
      - consul_instances
    image: dokken/debian-8
    command: /lib/systemd/systemd
    cgroupns_mode: host
    dockerfile: ../_shared/Dockerfile.j2
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
