---
platforms:
  - name: almalinux-8
    groups:
      - consul_instances
    image: dokken/almalinux-8
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
