---
- name: Converge
  hosts: all
  roles:
    - role: community.consul

  vars:
    # Force SysVinit, since systemd won't work in a Docker container
    ansible_service_mgr: sysvinit
    # We install netaddr in the prepare.yml playbook
    consul_install_dependencies: false
    # TODO: Probably we need to install syslog-ng/rsyslog first
    consul_syslog_enable: false
