---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      ansible.builtin.package:
        name: unzip
      become: true

    - name: Install netaddr dependency on controlling host
      ansible.builtin.pip:
        name: netaddr
      become: false
