---
name: Ansible Lint

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Temporary fix for roles
        run: |
          mkdir -p /home/runner/.ansible
          ln -s /home/runner/work/ansible-consul/ /home/runner/.ansible/roles

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@v6
